### ISSUE TITLE
Color of mytube logo not very visible

### ISSUE THREAD

**Issue by aelisya** [UWPCommunity/UWP-Companion#11]
**Problem**
When I go to YouTube with dark mode of edge (chrome) the logo is not very visible.

**Idea to solve the problem**
Change the color of the logo.

**Screenshot of the problem**
too dark.
![too dark](https://cdn.discordapp.com/attachments/534038175471894528/594881562345078924/Annotation_2019-06-30_152642.png)

**Comment by Arlodotexe** [comment]
I've updated the icon remotely. It's note easy to get perfect since the red and black clash. Is this better?
![image](https://user-images.githubusercontent.com/9384894/61765282-0dd6d100-ada2-11e9-93ee-f9455b5c6113.png)
