### ISSUE TITLE
redirection doesn't work with "open in new tab"

### ISSUE THREAD

**Issue by andrizmitnick** [UWPCommunity/UWP-Companion#5]

**Comment by Arlodotexe** [comment]
Could you provide more details on this?

**Comment by aelisya** [comment]
i have understand his problem.

For YouTube for instance open the main page select a video and right clic on it and open it in new tab.

This video will be displayed on YouTube and not redirected.

I don't know if it's normal i only reproduce his problem.

**Comment by Arlodotexe** [comment]
@aelisya Thank you for reporting this, I'll send an update out in a few days with this and a slew of other fixes.

Fixed in commit 82a17a74bb65c6e44ea2510026f32a04452188df
