### ISSUE TITLE
Honor system color

### ISSUE THREAD

**Issue by michaelb-ae** [UWPCommunity/UWP-Companion#9]
It would be nice in the extension theme to use the new CSS media function to honor the system color theme (dark or not).

https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme#Examples

**Comment by Arlodotexe** [comment]
I've been looking for a way to do this for a while now. I was looking in the wrong place it seems. Thank you!

**Comment by aelisya** [comment]
You're welcome, unfortunately this function is not highly visible in the documentation
